app:
  name: "point-of-sales"
  port: "8080"

db:
  host: "localhost"
  port: "5432"
  username: "root"
  password: "root"
  name: "nb_food_app"
  sslmode: "disable"
  max_idle_connection: 10
  max_open_connection: 25
  max_lifetime: 60
  max_idle_time: 60


